-- ====================================================================
-- SQL Setup untuk Fitur Sinkronisasi Galeri Foto (Dua Perangkat PWA)
-- ====================================================================
-- Cara Menjalankan:
-- 1. Buka Supabase Dashboard: https://supabase.com/dashboard/project/kgomclzfqfltbfgyitjz/sql
-- 2. Klik "New Query" (atau tombol +)
-- 3. Tempel (Paste) seluruh baris SQL di bawah ini, lalu klik "Run" (tombol hijau)
-- ====================================================================

-- 1. Buat tabel gallery_photos
CREATE TABLE IF NOT EXISTS public.gallery_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'favorit',
  src TEXT NOT NULL,
  likes INT DEFAULT 0,
  sender TEXT DEFAULT 'Kita',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE public.gallery_photos ENABLE ROW LEVEL SECURITY;

-- 3. Berikan izin baca, tambah, ubah, dan hapus foto untuk pengguna publik / anon
DROP POLICY IF EXISTS "Allow public read gallery_photos" ON public.gallery_photos;
CREATE POLICY "Allow public read gallery_photos" 
  ON public.gallery_photos FOR SELECT 
  USING (true);

DROP POLICY IF EXISTS "Allow public insert gallery_photos" ON public.gallery_photos;
CREATE POLICY "Allow public insert gallery_photos" 
  ON public.gallery_photos FOR INSERT 
  WITH CHECK (true);

DROP POLICY IF EXISTS "Allow public update gallery_photos" ON public.gallery_photos;
CREATE POLICY "Allow public update gallery_photos" 
  ON public.gallery_photos FOR UPDATE 
  USING (true);

DROP POLICY IF EXISTS "Allow public delete gallery_photos" ON public.gallery_photos;
CREATE POLICY "Allow public delete gallery_photos" 
  ON public.gallery_photos FOR DELETE 
  USING (true);

-- 4. Aktifkan Supabase Realtime agar setiap foto yang diupload di HP kamu
-- langsung muncul seketika di HP Alika tanpa perlu refresh halaman!
ALTER PUBLICATION supabase_realtime ADD TABLE public.gallery_photos;

-- ====================================================================
-- (Opsional) Setup Storage Bucket 'gallery' jika ingin simpan file di Supabase Storage
-- ====================================================================
INSERT INTO storage.buckets (id, name, public)
VALUES ('gallery', 'gallery', true)
ON CONFLICT (id) DO NOTHING;

DROP POLICY IF EXISTS "Allow public read gallery storage" ON storage.objects;
CREATE POLICY "Allow public read gallery storage"
  ON storage.objects FOR SELECT
  USING (bucket_id = 'gallery');

DROP POLICY IF EXISTS "Allow public insert gallery storage" ON storage.objects;
CREATE POLICY "Allow public insert gallery storage"
  ON storage.objects FOR INSERT
  WITH CHECK (bucket_id = 'gallery');
