"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";
import { 
  Mail, 
  Trash2, 
  RefreshCw, 
  MessageCircle, 
  Clock, 
  ArrowLeft, 
  Sparkles, 
  Lock, 
  Unlock,
  Check,
  Heart,
  Image as ImageIcon,
  Copy,
  ExternalLink,
  AlertCircle
} from "lucide-react";
import { supabase } from "@/lib/supabase";

export default function AdminPage() {
  const [messages, setMessages] = useState([]);
  const [loading, setLoading] = useState(true);
  const [waNumber, setWaNumber] = useState("628123456789");
  const [isEditingWa, setIsEditingWa] = useState(false);
  const [tempWa, setTempWa] = useState("");
  const [search, setSearch] = useState("");

  // Gallery Cloud state
  const [cloudPhotos, setCloudPhotos] = useState([]);
  const [galleryStatus, setGalleryStatus] = useState("checking"); // "ready" | "missing_table" | "error"
  const [copiedSql, setCopiedSql] = useState(false);
  const [deletingPhotoId, setDeletingPhotoId] = useState(null);

  // Optional PIN Protection (default PIN: alika or 1234)
  const [isUnlocked, setIsUnlocked] = useState(true);
  const [enteredPin, setEnteredPin] = useState("");
  const [pinError, setPinError] = useState(false);

  const sqlSetupCode = `-- 1. Buat tabel gallery_photos
CREATE TABLE IF NOT EXISTS public.gallery_photos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  category TEXT DEFAULT 'favorit',
  src TEXT NOT NULL,
  likes INT DEFAULT 0,
  sender TEXT DEFAULT 'Kita',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE public.gallery_photos ENABLE ROW LEVEL SECURITY;

-- 3. Kebijakan publik (baca, tambah, ubah, hapus)
CREATE POLICY "Allow public read gallery_photos" ON public.gallery_photos FOR SELECT USING (true);
CREATE POLICY "Allow public insert gallery_photos" ON public.gallery_photos FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update gallery_photos" ON public.gallery_photos FOR UPDATE USING (true);
CREATE POLICY "Allow public delete gallery_photos" ON public.gallery_photos FOR DELETE USING (true);

-- 4. Aktifkan Realtime untuk sinkronisasi seketika antar HP
ALTER PUBLICATION supabase_realtime ADD TABLE public.gallery_photos;`;

  const fetchMessages = async () => {
    setLoading(true);
    try {
      const res = await fetch("/api/messages");
      const data = await res.json();
      if (data.success) {
        setMessages(data.messages || []);
      }
    } catch (e) {
      console.error("Gagal load pesan:", e);
    } finally {
      setLoading(false);
    }
  };

  const fetchGallery = async () => {
    try {
      const { data, error } = await supabase
        .from("gallery_photos")
        .select("*")
        .order("created_at", { ascending: false });

      if (error) {
        if (error.code === "42P01" || error.message?.includes("does not exist")) {
          setGalleryStatus("missing_table");
        } else {
          setGalleryStatus("error");
        }
      } else {
        setCloudPhotos(data || []);
        setGalleryStatus("ready");
      }
    } catch (e) {
      setGalleryStatus("error");
    }
  };

  useEffect(() => {
    fetchMessages();
    fetchGallery();
    if (typeof window !== "undefined") {
      const savedWa = localStorage.getItem("alika_partner_wa");
      if (savedWa) {
        setWaNumber(savedWa);
      }
    }
  }, []);

  const handleDeleteMessage = async (id) => {
    if (!confirm("Hapus pesan ini dari riwayat?")) return;
    try {
      const res = await fetch(`/api/messages?id=${id}`, {
        method: "DELETE",
      });
      const data = await res.json();
      if (data.success) {
        setMessages(data.messages || []);
      }
    } catch (e) {
      console.error("Gagal menghapus:", e);
    }
  };

  const handleDeletePhoto = async (id) => {
    if (!confirm("Hapus foto ini dari Cloud Supabase? Foto akan hilang dari kedua HP.")) return;
    setDeletingPhotoId(id);
    try {
      const { error } = await supabase
        .from("gallery_photos")
        .delete()
        .eq("id", id);

      if (!error) {
        setCloudPhotos((prev) => prev.filter((p) => p.id !== id));
      }
    } catch (e) {
      console.error("Gagal menghapus foto:", e);
    } finally {
      setDeletingPhotoId(null);
    }
  };

  const handleCopySql = () => {
    if (navigator.clipboard) {
      navigator.clipboard.writeText(sqlSetupCode);
      setCopiedSql(true);
      setTimeout(() => setCopiedSql(false), 3000);
    }
  };

  const handleSaveWa = (e) => {
    e.preventDefault();
    if (!tempWa.trim()) return;
    const cleanNumber = tempWa.replace(/[^0-9]/g, "");
    setWaNumber(cleanNumber);
    if (typeof window !== "undefined") {
      localStorage.setItem("alika_partner_wa", cleanNumber);
    }
    setIsEditingWa(false);
  };

  const filteredMessages = messages.filter((m) =>
    m.text.toLowerCase().includes(search.toLowerCase())
  );

  return (
    <div className="min-h-screen bg-[#fdf2f4] text-[#4a2835] p-4 sm:p-8 selection:bg-pink-300 selection:text-pink-900">
      <div className="max-w-4xl mx-auto space-y-6">
        
        {/* Top Header Navigation */}
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 bg-white/80 backdrop-blur-md p-5 rounded-3xl border border-pink-200/80 shadow-xs">
          <div className="flex items-center gap-3">
            <Link
              href="/"
              className="p-2.5 rounded-2xl bg-pink-50 text-pink-700 hover:bg-pink-100 transition-colors flex items-center gap-1.5 text-xs font-semibold"
              title="Kembali ke web utama"
            >
              <ArrowLeft className="w-4 h-4" />
              <span>Ke Website</span>
            </Link>
            <div>
              <h1 className="text-lg sm:text-xl font-bold text-zinc-800 flex items-center gap-2">
                <span>Pusat Kontrol &amp; Admin</span>
                <span className="text-xs px-2.5 py-0.5 rounded-full bg-pink-100 text-pink-700 font-mono font-bold">
                  Admin
                </span>
              </h1>
              <p className="text-xs text-zinc-500">
                Kelola pesan cinta, sinkronisasi foto 2 perangkat, dan nomor WhatsApp
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={() => { fetchMessages(); fetchGallery(); }}
              disabled={loading}
              className="px-3.5 py-2 rounded-xl bg-pink-50 hover:bg-pink-100 text-pink-700 text-xs font-semibold flex items-center gap-1.5 transition-colors"
            >
              <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
              <span>Refresh Semua</span>
            </button>
          </div>
        </div>

        {/* CLOUD GALLERY SYNC STATUS CARD */}
        <div className="bg-white/80 backdrop-blur-md p-5 sm:p-6 rounded-3xl border border-pink-200/80 shadow-xs space-y-4">
          <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3">
            <div className="flex items-center gap-3">
              <div className="w-10 h-10 rounded-2xl bg-pink-100 text-pink-600 flex items-center justify-center shrink-0">
                <ImageIcon className="w-5 h-5" />
              </div>
              <div>
                <h3 className="text-sm font-bold text-zinc-800 flex items-center gap-2">
                  <span>Sinkronisasi Foto Cloud (Supabase)</span>
                  {galleryStatus === "ready" && (
                    <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-emerald-100 text-emerald-700 flex items-center gap-1">
                      <span className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse"></span>
                      Aktif (Sinkron 2 HP)
                    </span>
                  )}
                  {galleryStatus === "missing_table" && (
                    <span className="px-2.5 py-0.5 rounded-full text-[11px] font-bold bg-amber-100 text-amber-800 flex items-center gap-1">
                      Perlu 1x Setup SQL
                    </span>
                  )}
                </h3>
                <p className="text-xs text-zinc-500">
                  {galleryStatus === "ready"
                    ? `${cloudPhotos.length} foto tersimpan di Cloud Supabase dan otomatis tampil di kedua perangkat.`
                    : "Supaya foto yang diupload di HP kamu otomatis muncul di HP Alika, aktifkan tabel di Supabase."}
                </p>
              </div>
            </div>

            {galleryStatus === "ready" && (
              <button
                onClick={fetchGallery}
                className="self-start sm:self-auto px-3.5 py-1.5 rounded-xl bg-pink-50 hover:bg-pink-100 text-pink-700 text-xs font-semibold flex items-center gap-1.5 transition"
              >
                <RefreshCw className="w-3.5 h-3.5" />
                <span>Cek Foto Cloud</span>
              </button>
            )}
          </div>

          {/* MISSING TABLE SETUP BANNER */}
          {galleryStatus === "missing_table" && (
            <div className="p-4 sm:p-5 rounded-2xl bg-amber-50/80 border border-amber-200 text-xs space-y-3">
              <div className="flex items-start gap-2.5">
                <AlertCircle className="w-4 h-4 text-amber-600 shrink-0 mt-0.5" />
                <div className="space-y-1">
                  <p className="font-bold text-amber-900">
                    Tabel <code className="bg-white/80 px-1 rounded">gallery_photos</code> belum dibuat di Supabase
                  </p>
                  <p className="text-amber-800 leading-relaxed">
                    Hanya perlu 1 langkah mudah! Salin perintah SQL di bawah ini, buka SQL Editor di Supabase, lalu klik tombol <b>Run</b>. Seketika itu juga, foto yang diupload akan otomatis terhubung ke kedua perangkat.
                  </p>
                </div>
              </div>

              <div className="relative bg-zinc-900 text-zinc-200 p-3.5 rounded-xl font-mono text-[11px] overflow-x-auto max-h-48 border border-zinc-700">
                <pre>{sqlSetupCode}</pre>
                <button
                  onClick={handleCopySql}
                  className="absolute top-2 right-2 px-3 py-1.5 rounded-lg bg-pink-600 hover:bg-pink-700 text-white font-sans text-xs font-semibold flex items-center gap-1 shadow transition"
                >
                  {copiedSql ? (
                    <>
                      <Check className="w-3.5 h-3.5 text-white" />
                      <span>Tersalin!</span>
                    </>
                  ) : (
                    <>
                      <Copy className="w-3.5 h-3.5" />
                      <span>Salin SQL</span>
                    </>
                  )}
                </button>
              </div>

              <div className="flex flex-wrap items-center gap-2 pt-1">
                <a
                  href="https://supabase.com/dashboard/project/kgomclzfqfltbfgyitjz/sql"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="inline-flex items-center gap-1.5 px-4 py-2 rounded-xl bg-pink-600 hover:bg-pink-700 text-white text-xs font-bold transition shadow-xs"
                >
                  <span>Buka Supabase SQL Editor</span>
                  <ExternalLink className="w-3.5 h-3.5" />
                </a>
                <button
                  onClick={fetchGallery}
                  className="px-4 py-2 rounded-xl bg-white hover:bg-zinc-50 border border-amber-300 text-amber-900 text-xs font-semibold transition"
                >
                  Sudah Dijalankan? Klik Refresh
                </button>
              </div>
            </div>
          )}

          {/* LIST FOTO CLOUD */}
          {galleryStatus === "ready" && cloudPhotos.length > 0 && (
            <div className="pt-2 border-t border-pink-100">
              <p className="text-xs font-bold text-zinc-700 mb-3">Foto yang Sedang Aktif di Cloud:</p>
              <div className="grid grid-cols-2 sm:grid-cols-4 md:grid-cols-6 gap-3">
                {cloudPhotos.map((photo) => (
                  <div key={photo.id} className="relative group rounded-xl overflow-hidden bg-pink-50 border border-pink-200 aspect-square">
                    <img src={photo.src} alt={photo.title} className="w-full h-full object-cover" />
                    <div className="absolute inset-0 bg-black/50 opacity-0 group-hover:opacity-100 transition-opacity flex flex-col justify-between p-2">
                      <span className="text-[10px] text-white font-medium truncate">{photo.title}</span>
                      <button
                        onClick={() => handleDeletePhoto(photo.id)}
                        disabled={deletingPhotoId === photo.id}
                        className="self-end p-1.5 rounded-lg bg-red-500 hover:bg-red-600 text-white transition disabled:opacity-50"
                        title="Hapus foto dari cloud"
                      >
                        <Trash2 className="w-3.5 h-3.5" />
                      </button>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* WhatsApp Setup Card */}
        <div className="bg-white/80 backdrop-blur-md p-5 rounded-3xl border border-pink-200/80 shadow-xs flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-emerald-100 text-emerald-600 flex items-center justify-center shrink-0">
              <MessageCircle className="w-5 h-5" />
            </div>
            <div>
              <p className="text-xs font-bold text-zinc-800">
                Nomor WhatsApp Tujuan:{" "}
                <span className="font-mono text-emerald-700">+{waNumber}</span>
              </p>
              <p className="text-[11px] text-zinc-500">
                Nomor ini yang akan dihubungi saat Alika menekan tombol "Kirimkan ke WhatsApp Dia"
              </p>
            </div>
          </div>

          <div>
            {!isEditingWa ? (
              <button
                onClick={() => {
                  setTempWa(waNumber);
                  setIsEditingWa(true);
                }}
                className="px-4 py-2 rounded-xl bg-pink-100 hover:bg-pink-200 text-pink-700 text-xs font-semibold transition-colors"
              >
                Ganti Nomor WA
              </button>
            ) : (
              <form onSubmit={handleSaveWa} className="flex gap-2">
                <input
                  type="text"
                  placeholder="628123456789"
                  value={tempWa}
                  onChange={(e) => setTempWa(e.target.value)}
                  className="px-3 py-1.5 rounded-xl border border-pink-200 text-xs font-mono bg-white"
                />
                <button
                  type="submit"
                  className="px-3 py-1.5 rounded-xl bg-pink-500 hover:bg-pink-600 text-white text-xs font-semibold"
                >
                  Simpan
                </button>
                <button
                  type="button"
                  onClick={() => setIsEditingWa(false)}
                  className="px-3 py-1.5 rounded-xl bg-zinc-100 hover:bg-zinc-200 text-zinc-600 text-xs"
                >
                  Batal
                </button>
              </form>
            )}
          </div>
        </div>

        {/* Search Bar & Total Messages */}
        <div className="flex items-center justify-between gap-4">
          <div className="text-xs font-bold text-zinc-600">
            Total Masuk: <span className="text-pink-600 font-mono text-sm">{messages.length}</span> Pesan
          </div>
          <input
            type="text"
            placeholder="Cari kata di pesan..."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            className="px-4 py-2 rounded-xl bg-white border border-pink-200 text-xs w-48 sm:w-64 focus:outline-none focus:ring-2 focus:ring-pink-300"
          />
        </div>

        {/* Message Cards List */}
        <div className="space-y-4">
          {loading ? (
            <div className="py-16 text-center text-xs text-zinc-400">
              Memuat pesan...
            </div>
          ) : filteredMessages.length === 0 ? (
            <div className="py-16 text-center bg-white/60 rounded-3xl border border-pink-100 space-y-2">
              <span className="text-4xl">💌</span>
              <p className="text-sm font-semibold text-zinc-600">
                Belum ada pesan balasan
              </p>
              <p className="text-xs text-zinc-400 max-w-sm mx-auto">
                Saat Alika mengetik balasan di website, pesannya akan langsung tersimpan dan muncul di sini.
              </p>
            </div>
          ) : (
            filteredMessages.map((msg) => (
              <div
                key={msg.id}
                className="p-5 sm:p-6 rounded-3xl bg-white border border-pink-200 shadow-sm space-y-3 relative group transition-all hover:shadow-md"
              >
                <div className="flex items-center justify-between border-b border-pink-50 pb-3">
                  <div className="flex items-center gap-2">
                    <span className="text-2xl">{msg.reaction || "❤️"}</span>
                    <div>
                      <span className="text-sm font-bold text-zinc-800">
                        {msg.sender || "Alika"}
                      </span>
                      <div className="flex items-center gap-1 text-[11px] text-zinc-400 font-mono">
                        <Clock className="w-3 h-3" />
                        <span>{msg.timestamp || `${msg.date} ${msg.time}`}</span>
                      </div>
                    </div>
                  </div>

                  <button
                    onClick={() => handleDeleteMessage(msg.id)}
                    className="p-2 rounded-xl text-zinc-300 hover:text-rose-500 hover:bg-rose-50 transition-colors"
                    title="Hapus pesan ini"
                  >
                    <Trash2 className="w-4 h-4" />
                  </button>
                </div>

                <div className="p-4 rounded-2xl bg-[#fffbfd] border border-pink-100 text-sm sm:text-base text-zinc-700 leading-relaxed font-sans">
                  "{msg.text}"
                </div>
              </div>
            ))
          )}
        </div>

        {/* Info Note */}
        <div className="p-4 rounded-2xl bg-pink-100/60 border border-pink-200 text-center text-xs text-pink-800">
          💡 Catatan: Halaman ini hanya untuk kamu (buka lewat alamat <code className="font-mono font-bold bg-white/70 px-1.5 py-0.5 rounded">/admin</code>). Halaman ini tidak terhubung ke menu atau tombol apa pun di halaman utama yang dilihat Alika.
        </div>

      </div>
    </div>
  );
}
